service: my-service

provider:
  name: aws
  runtime: nodejs18.x

functions:
  mainHandler:
    handler: dist/index.handler
    events:
      - http:
          path: initial-songs
          method: post
      - http:
          path: create-playlist
          method: post


plugins:
  - serverless-offline

custom:
  serverless-offline:
    noPrependStageInUrl: true
