const examples = [
    'barbecue with friends',
    'pool day with the family',
    'going to the beach with classmates',
    "long road trip adventure",
    "chill study session alone",
    "relaxing yoga retreat",
    "energetic morning run",
    "unwinding after work",
    "evening cooking dinner",
    "quiet reading time",
    "wild weekend party",
    "late-night gaming session",
    "snowy day indoors",
    "sunny afternoon picnic",
    "backyard camping night",
    "training for a marathon",
    "celebrating a promotion",
    "fun day at the zoo",
    "stargazing on a clear night",
    "holiday season shopping",
    "groovy dance practice",
    "exploring a new city",
    "packing for vacation",
    "decorating for Christmas",
    "cozy rainy day",
    "summer music festival",
    "hiking through the forest",
    "weekend gardening session",
    "candlelit dinner date",
    "bonfire with college friends",
    "lazy Sunday brunch",
    "intense weightlifting session",
    "prepping for a date",
    "midnight snack cooking",
    "sailing on the open sea",
    "fishing at the lake",
    "cleaning up the house",
    "studying for finals week",
    "cozy coffee shop vibes",
    "family reunion gathering",
    "baking cookies for Christmas",
    "night drive through the city",
    "afternoon painting session",
    "biking in the countryside",
    "cheering for your team",
    "preparing a birthday surprise",
    "meditating during sunset",
    "wine tasting in Napa",
    "mountain climbing challenge",
    "cuddling with pets",
    "watching a romantic movie",
    "exploring a flea market",
    "beach volleyball competition",
    "early bird breakfast making",
    "scary Halloween party",
    "first date at a café",
    "playing board games",
    "cooking a family recipe",
    "watching the sunrise",
    "karaoke night with friends",
    "relaxing at a spa",
    "prepping for a job interview",
    "skydiving adrenaline rush",
    "skating in the park",
    "enjoying a jazz concert",
    "writing a new novel",
    "visiting grandparents' house",
    "building a snowman",
    "camping in the wilderness",
    "celebrating a wedding anniversary",
    "visiting a farmers market",
    "backpacking through Europe",
    "wine and paint night",
    "movie marathon weekend",
    "cheering at a sports game",
    "DIY home renovation",
    "celebrating a new job",
    "surfing at the beach",
    "romantic walk in the park",
    "learning a new language",
    "brewing some homemade beer",
    "watching a comedy show",
    "planting new spring flowers",
    "strolling through an art museum",
    "cozying up with a book",
    "observing a quiet snowfall",
    "shopping in downtown",
    "visiting a theme park",
    "tailgating at the game",
    "stargazing at the observatory",
    "scuba diving adventure",
    "playing video games",
    "building a model ship",
    "hosting a charity event",
    "ice-skating in winter",
    "fall leaf peeping trip",
    "making homemade pizza",
    "crafting DIY gifts",
    "volunteering at the shelter",
    "throwing a surprise party",
    "sipping coffee at sunrise",
    "feeling the sand between your toes",
    "planting a vegetable garden",
    "trekking through the jungle",
    "soaking in a hot tub",
    "dancing at a salsa club",
    "riding a horse on the beach",
    "reading a mystery novel",
    "celebrating a friend's baby shower",
    "spinning pottery on the wheel",
    "browsing through a bookstore",
    "making homemade ice cream",
    "laughing at a stand-up comedy",
    "participating in a bake-off",
    "reminiscing with high school friends",
    "hosting a Thanksgiving dinner",
    "enjoying a lazy Saturday morning",
    "walking the dog in the park",
    "jumping on a trampoline",
    "solving a crossword puzzle",
    "kayaking on a calm lake",
    "celebrating a festive Diwali",
    "painting a mural",
    "exercising with a fitness group",
    "bird watching in the forest",
    "jogging in the early morning",
    "practicing magic tricks",
    "brewing a perfect cup of tea",
    "making s'mores by the fire",
    "learning to play guitar",
    "baking bread from scratch",
    "driving on a scenic route",
    "knitting a new sweater",
    "visiting a local brewery",
    "trying out new makeup looks",
    "exploring an antique shop",
    "pampering with a beauty routine",
    "jazzing it up at a music club",
    "indulging in a chocolate tasting",
    "lazing around on a hammock",
    "hitting the boxing gym",
    "jogging with your dog",
    "potluck dinner with neighbors",
    "writing in your journal",
    "brewing morning coffee",
    "hosting a game night",
    "biking around the lake",
    "creating a scrapbook",
    "doing an at-home workout",
    "attending a tech conference",
    "going to an indie concert",
    "exploring a botanical garden",
    "having a sleepover with friends",
    "having a picnic in the park",
    "practicing ballet moves",
    "playing chess in the park",
    "visiting a historical site",
    "going on a nature walk",
    "doing a home makeover",
    "kicking back at a jazz festival",
    "touring a wine vineyard",
    "sitting by a bonfire",
    "going to a farmers' market",
    "preparing for a camping trip",
    "making homemade jam",
    "visiting a science museum",
    "strolling along a river",
    "rearranging the living room",
    "doing a jigsaw puzzle",
    "sketching at a park",
    "visiting a petting zoo",
    "making beaded jewelry",
    "watching a soccer game",
    "learning to juggle",
    "training for a triathlon",
    "going to a silent disco",
    "visiting a haunted house",
    "bird watching at dawn",
    "making a homemade pasta",
    "going on a photography walk",
    "having a pillow fight",
    "practicing archery",
    "exploring a castle",
    "collecting seashells on the beach",
    "creating a home cinema",
    "doing a fashion photoshoot",
    "attending a poetry reading",
    "baking a birthday cake",
    "going on a ghost tour",
    "enjoying a city rooftop view",
    "building a Lego castle",
    "making origami art",
    "attending a book club",
    "going on a coffee date",
    "prepping for a charity run",
    "catching a magic show",
    "riding a roller coaster",
    "planning a surprise party",
    "exploring a science fair",
    "having a pool party",
    "going on a safari adventure",
    "enjoying a food festival",
    "picking apples in the orchard",
    "cooking a gourmet meal",
    "going to a fashion show",
    "trying out rock climbing",
    "exploring a cave",
    "crafting with kids",
    "creating a vision board",
    "watching a basketball game",
    "having a tea party",
    "practicing Tai Chi in the park",
    "volunteering at a food bank",
    "reading a sci-fi novel",
    "watching a parade",
    "practicing drumming",
    "going on a hot air balloon ride",
    "enjoying a lakeside picnic",
    "exploring a planetarium",
    "picking berries at a farm",
    "rehearsing for a play",
    "going on a blind date",
    "practicing golf swings",
    "attending a cooking class",
    "making a snow angel",
    "going on a date to the aquarium",
    "shopping at an outdoor market",
    "making homemade candles",
    "starting a DIY project",
    "learning calligraphy",
    "having a family movie night",
    "exploring a zoo",
    "feeding ducks at the park",
    "learning to sew",
    "making a sandcastle",
    "exploring a night market",
    "having a tropical beach day",
    "drawing in a sketchbook",
    "prepping for a garage sale",
    "taking a painting class",
    "attending a yoga class",
    "taking a dance lesson",
    "going to a high school reunion",
    "enjoying a spa day",
    "going on a picnic date",
    "playing frisbee in the park",
    "practicing a choir performance",
    "visiting a cat café",
    "relaxing in a sauna",
    "riding a Ferris wheel",
    "having a stay-at-home date",
    "decorating Easter eggs",
    "attending a car show",
    "making a homemade soup",
    "relaxing with a face mask",
    "writing poetry in a coffee shop",
    "collecting vinyl records",
    "watching the sunset from a hill",
    "going to a puppy playdate",
    "going to a charity gala",
    "planting a flower garden",
    "enjoying a firework display",
    "practicing meditation",
    "going to a beer festival",
    "going to a pumpkin patch",
    "watching a tennis match",
    "running a charity marathon",
    "trying a new workout routine",
    "baking cupcakes for a party",
    "visiting a carnival",
    "playing paintball with friends",
    "making homemade sushi",
    "going to a comedy club",
    "taking a pottery class",
    "doing a home workout",
    "watching a live concert",
    "taking a scenic hike",
    "watching a documentary",
    "learning magic tricks",
    "making homemade lemonade",
    "going to a music festival",
    "going to a ballet performance",
    "going to a pet adoption event",
    "going on a museum tour",
    "taking a cooking class",
    "going on a hayride",
    "picking out a Christmas tree",
    "having a Christmas movie marathon",
    "going ice fishing",
    "going on a holiday light tour",
    "hosting a New Year's Eve party",
    "going to a winter carnival",
    "going to a spring garden show",
    "going on a Valentine's Day date",
    "going to a Mardi Gras parade",
    "going to a Easter egg hunt",
    "going on a Mother's Day brunch",
    "going to a summer county fair",
    "going to a Halloween party",
    "going to a Christmas carol concert",
    "visiting a pumpkin farm",
    "baking a cake for Mother's Day",
    "planning a birthday surprise",
    "hosting a costume party",
    "cooking a Sunday roast",
    "visiting a craft fair",
    "celebrating graduation day",
    "going to a circus show",
    "celebrating an engagement",
    "baking cookies for a bake sale",
    "watching a magic show",
    "playing poker with friends",
    "making tie-dye shirts",
    "going to a hip hop concert",
    "celebrating a friend's promotion",
    "having a tropical luau",
    "celebrating a new home",
    "baking a pie for a potluck",
    "playing basketball at the park",
    "going to a food truck festival",
    "watching a broadway musical",
    "going to a rodeo",
    "attending a formal dinner",
    "reading a classic novel",
    "going to a rave party",
    "hosting a tapas night",
    "celebrating a retirement party",
    "making homemade pasta",
    "going to a masquerade ball",
    "taking a bubble bath",
    "creating a photo album",
    "practicing a new yoga pose",
    "playing in a band",
    "watching a boxing match",
    "visiting a butterfly farm",
    "going on a wine tour",
    "making homemade pizza",
    "strolling through a flower festival",
    "watching a horse race",
    "going to a baseball game",
    "attending a wedding reception",
    "prepping for a desert safari",
    "at a high-stakes poker game",
    "watching a meteor shower",
    "learning to play the violin",
    "visiting a haunted house",
    "outdoor rock climbing",
    "working on a car restoration",
    "at a TED talk",
    "trying out capoeira",
    "browsing a vintage clothes market",
    "participating in a chess tournament",
    "going on a Ferris wheel",
    "practicing fencing",
    "going to a cabaret",
    "cooking an authentic Indian meal",
    "gathering around a bonfire",
    "visiting a vineyard",
    "paddleboarding on the lake",
    "making homemade cosmetics",
    "at a high school musical",
    "playing a match of badminton",
    "attending a lecture",
    "in a singing competition",
    "practicing tightrope walking",
    "on a scuba diving expedition",
    "in a glassblowing class",
    "at a drag race",
    "taking a salsa class",
    "celebrating Mardi Gras",
    "going to a bird sanctuary",
    "in a motorcycle rally",
    "enjoying a tango show",
    "creating pottery art",
    "in a ballet class",
    "taking horse riding lessons",
    "watching a live wrestling match",
    "in a figure drawing class",
    "playing beach soccer",
    "creating street art murals",
    "on a cross-country skiing trip",
    "making a DIY birdhouse",
    "working on a farm",
    "learning to juggle",
    "at a breakdancing workshop",
    "making homemade ice cream",
    "going to a drumming circle",
    "observing a lunar eclipse",
    "doing a crossfit workout",
    "at a DJing masterclass",
    "going to a political rally",
    "on a safari photo tour",
    "learning to make origami",
    "in a latte art class",
    "visiting a reptile zoo",
    "at a pottery wheel workshop",
    "learning ballroom dance",
    "making paper mache crafts",
    "going to a sculpture garden",
    "at an amateur astronomy session",
    "on a wildflower hiking trip",
    "visiting a renaissance fair",
    "practicing Tai Chi",
    "making homemade soap",
    "on a ziplining adventure",
    "learning to make sushi",
    "making stained glass art",
    "at a live jazz club",
    "in a community choir practice",
    "practicing archery",
    "in a watercolor painting class",
    "on a whale-watching boat tour",
    "in a sailing lesson",
    "participating in a trivia night",
    "doing a spin class",
    "on a fall foliage tour",
    "at an improv comedy class",
    "exploring botanical gardens",
    "taking a Pilates class",
    "on a ghost town exploration",
    "practicing calligraphy",
    "visiting a science museum",
    "in a martial arts class",
    "doing a landscape photography shoot",
    "visiting an old castle",
    "making homemade candles",
    "attending a poetry slam",
    "exploring a cave",
    "going to a craft beer tasting",
    "making a scrapbook",
    "participating in a dodgeball game",
    "visiting a tropical rainforest",
    "at a local farmers market",
    "on a snowboarding trip",
    "doing a kickboxing workout",
    "at a film noir movie night",
    "making a quilt",
    "visiting an art installation",
    "at a local food festival",
    "practicing meditation",
    "on a butterfly watching hike",
    "at a storytelling event",
    "watching a ballet performance",
    "at an open mic night",
    "making terrariums",
    "doing aerial yoga",
    "at a charity bake sale",
    "practicing parkour",
    "making homemade bread",
    "visiting a jazz festival",
    "at a live theater performance",
    "doing Tai Chi in the park",
    "learning magic tricks",
    "visiting a honey farm",
    "at a film screening",
    "in a comedy improv class",
    "doing stand-up paddleboarding",
    "at a science fair",
    "visiting a butterfly exhibit",
    "at a silent disco",
    "in a birdwatching tour",
    "visiting a historic fort",
    "in a rock climbing class",
    "at a classic film screening",
    "doing yoga in the park",
    "visiting a rose garden",
    "on a horse carriage ride",
    "making homemade pottery",
    "practicing circus arts",
    "in a live cooking class",
    "going to a masquerade ball",
    "learning aerial silks",
    "in a beer brewing class",
    "at a vintage car show",
    "visiting a hot air balloon festival",
    "in a fencing lesson",
    "watching a symphony orchestra",
    "visiting a folk music festival",
    "at a meditation retreat",
    "learning roller skating",
    "going to a blues concert",
    "visiting a haunted mansion",
    "in a printmaking workshop",
    "going to a puppet show",
    "visiting a model train show",
    "making a mosaic art piece",
    "visiting a kite festival",
    "in a step dance class",
    "at a silent movie night",
    "participating in a pub quiz",
    "going to a lantern festival",
    "in a carpentry workshop",
    "visiting a wildflower field",
    "making macrame wall hangings",
    "in a salsa dance class",
    "visiting a kite flying contest",
    "going to a Renaissance festival",
    "visiting a lavender farm",
    "in a mystery dinner theater",
    "learning to play the harmonica",
    "visiting a natural history museum",
    "in a costume making workshop",
    "visiting a cherry blossom festival",
    "attending a belly dancing class",
    "going to a cultural heritage festival",
    "learning to weave on a loom",
    "in a candle making workshop",
    "going to a burlesque show",
    "visiting an orchid exhibition",
    "learning to make traditional pottery",
    "going to a drum and bass concert",
    "visiting a record fair",
    "making homemade cheese",
    "visiting a hot springs resort",
    "at a mime performance",
    "making a hand-knitted scarf",
    "going to a silent film festival",
    "learning to play the ukulele",
    "in a graffiti art class",
    "visiting a mineral and gem show",
    "doing a fitness boot camp",
    "at a hip hop dance class",
    "watching an air show",
    "doing sand art on the beach",
    "going to a reggae concert",
    "visiting a craft fair",
    "learning about beekeeping",
    "going to a puppet theater",
    "making traditional handcrafted jewelry",
    "at a cooking demonstration",
    "watching a stunt show",
    "in a ballet folklorico class",
    "visiting a tulip field",
    "learning about wine making",
    "making a handmade leather bag",
    "visiting a comic book convention",
    "learning to play the sitar",
    "at a letterpress printing workshop",
    "going to a roller derby match",
    "visiting an anime convention",
    "in a flamenco dance class",
    "making artisan chocolates",
    "going to a folk dance performance",
    "visiting a living history museum",
    "in a trapeze class",
    "visiting a dahlia garden",
    "learning the art of bonsai",
    "going to a silent auction",
    "attending a choral concert",
    "learning how to make a pinata",
    "going to a craft beer festival",
    "at a mime workshop",
    "visiting a sunflower field",
    "in a jazz dance class",
    "going to a modern art gallery",
    "watching a shadow puppet show",
    "making homemade jam",
    "learning to play the mandolin",
    "visiting a music box museum",
    "going to a tap dance show",
    "in a stained glass workshop",
    "watching a magic show",
    "visiting a wildlife refuge",
    "learning to play the harp",
    "going to a poetry reading",
    "watching a stunt kite performance",
    "visiting an antique book fair",
    "learning to do a magic trick",
    "going to a gospel music concert",
    "visiting a chocolate factory",
    "making a traditional quilt",
    "at a shadow theater performance",
    "visiting a sculpture park",
    "learning to make hand-pulled noodles",
    "going to a percussion concert",
    "learning to make paper flowers",
    "going to a Shakespearean play",
    "visiting a puppet museum",
    "at a capoeira demonstration",
    "learning to play the bagpipes",
    "going to a zydeco music festival",
    "attending a food truck rally",
    "visiting a butterfly garden",
    "going to a kite festival",
    "learning to play the cello",
    "horseback riding in the countryside",
    "attending a ceramics class",
    "visiting a submarine museum",
    "at a flamenco dance show",
    "making homemade pasta",
    "going to an alpaca farm",
    "visiting an insect museum",
    "watching a rugby match",
    "going on a geocaching adventure",
    "learning to play the accordion",
    "visiting a planetarium",
    "going to a fiddle contest",
    "working at a soup kitchen",
    "participating in a color run",
    "learning the art of origami",
    "making homemade pretzels",
    "learning to skateboard",
    "participating in a hackathon",
    "visiting a bonsai exhibition",
    "doing a canopy tour",
    "learning sign language",
    "visiting an aquarium",
    "going to a Celtic music concert",
    "making homemade sausages",
    "participating in a clean-up drive",
    "going to a fairground",
    "learning to play the flute",
    "making homemade candles",
    "participating in a drum circle",
    "visiting an art fair",
    "learning to ice sculpt",
    "going to a cabaret show",
    "visiting a maritime museum",
    "participating in a poetry workshop",
    "learning to make sushi",
    "going to a puppetry festival",
    "visiting a pinball museum",
    "making homemade pickles",
    "going to a renaissance fair",
    "learning to fly a drone",
    "visiting a lighthouse",
    "going to a symphony concert",
    "learning to make a terrarium",
    "watching a fencing tournament",
    "going to a craft brewery",
    "learning to draw manga",
    "visiting a mineral exhibition",
    "watching a laser show",
    "going to a music jam session",
    "learning to write calligraphy",
    "visiting a classic car show",
    "going to a rodeo",
    "learning to make stained glass",
    "visiting a waterfall",
    "watching a dog show",
    "going to a circus",
    "learning to knit",
    "visiting a tea ceremony",
    "watching a fireworks display",
    "going to a reggae festival",
    "learning to sculpt clay",
    "visiting a space observatory",
    "watching a parade",
    "going to a country music concert",
    "learning to whittle",
    "visiting a cheese factory",
    "watching a horse race",
    "going to a burlesque show",
    "visiting a tulip farm",
    "watching a jousting tournament",
    "going to a polka festival",
    "learning to make homemade beer",
    "visiting a coral reef",
    "watching a sailboat race",
    "going to a bluegrass festival",
    "learning to make felted wool animals",
    "visiting a chili cook-off",
    "watching a caber toss",
    "going to a fashion show",
    "learning to do macrame",
    "visiting a windmill",
    "going to a blues jam",
    "learning to make beaded jewelry",
    "watching a polo match",
    "going to a mural festival",
    "learning to make mosaics",
    "visiting a honeybee farm",
    "going to a folk music festival",
    "learning to make origami animals",
    "exploring a ghost town",
    "going to a stand-up comedy night",
    "learning to make paper airplanes",
    "visiting a lavender farm",
    "watching a dragon boat race",
    "going to a puppet show",
    "learning to make origami cranes",
    "visiting a peony garden",
    "going to a storytelling festival",
    "learning to juggle",
    "visiting a haunted house",
    "going to a gourmet food festival",
    "learning to play the harmonica",
    "visiting a cranberry bog",
    "learning to play the banjo",
    "learning to make lace",
    "visiting a pyrotechnics display",
    "learning to play the pan flute",
    "visiting a teddy bear museum",
    "learning to make chainmail",
    "visiting a barista competition",
    "watching a motorcross event",
    "watching a BMX competition",
    "going to a historic reenactment",
    "learning to make pop-up cards",
    "visiting a street art exhibition",
    "visiting a kite making workshop",
    "watching a speedboat race",
    "learning to play the xylophone",
    "going to a salsa dance class",
    "watching a robotics competition",
    "going to a feng shui workshop",
    "learning to make wire sculptures",
    "visiting a stunt car show",
    "going to a neon art exhibit",
    "watching a roller derby game",
    "going to a sand art festival",
    "learning to make string art",
    "watching a trapeze show",
    "visiting a mime class",
    "going to a soapbox derby",
    "learning to make shadow puppets",
    "watching a chess tournament",
    "learning to make finger puppets",
    "visiting an orchid exhibition",
    "watching a cricket match",
    "going to a vintage fashion show",
    "learning to tie-dye shirts",
    "visiting a pearl farm",
    "visiting a magic show",
    "going to a farmers market",
    "learning to play the ukulele",
    "visiting a lantern festival",
    "visiting a wildlife sanctuary",
    "going to a silent disco",
    "learning to play the sitar",
    "visiting a gem and mineral show",
    "watching a windsurfing competition",
    "going to a book binding workshop",
    "learning to do basket weaving",
    "visiting a sunflower field",
    "watching a hot air balloon race",
    "going to a classic car auction",
    "learning to make glass beads",
    "visiting a film set",
    "going to a storytelling session",
    "learning to play the mandolin",
    "visiting a robot exhibition",
    "going to a craft beer festival",
    "learning to make homemade jam",
    "visiting a jazz club",
    "going to a botanical garden",
    "visiting a butterfly farm",
    "going to a tai chi class",
    "learning to weave a tapestry",
    "visiting a bonsai workshop",
    "watching a belly dance show",
    "going to a sand art workshop",
    "learning to make marionettes",
    "visiting a kite exhibition",
    "watching a blues guitar workshop",
    "going to a juggling workshop",
    "learning to play the harpsichord",
    "visiting a batik workshop",
    "watching a yoyo competition",
    "going to a graffiti art tour",
    "learning to make homemade pasta",
    "visiting a quilt exhibition",
    "watching a traditional puppet show",
    "going to a sculpture park",
    "learning to do origami",
    "visiting a haiku reading",
    "watching a tango dance competition",
    "going to a taxidermy workshop",
    "learning to play the theremin",
    "visiting a historic ship tour",
    "watching a lacrosse game",
    "going to a comic book convention",
    "learning to play the didgeridoo",
    "visiting a letterpress workshop",
    "watching a rugby league match",
    "going to a puppet making workshop",
    "learning to make pottery",
    "visiting a spice market",
    "watching a 3D street art creation",
    "going to a silent film screening",
    "learning to play the accordion",
    "visiting a carillon concert",
    "going to a mime show",
    "learning to make homemade bread",
    "watching a fencing tournament",
    "going to a 3D printing workshop",
    "learning to play the bagpipes",
    "watching a magic trick workshop",
    "going to a choral music concert",
    "learning to make bonsai trees",
    "visiting a neon sign museum",
    "learning to paint watercolors",
    "visiting a pipe organ concert",
    "going to a fairytale reenactment",
    "learning to make sushi",
    "watching a paragliding competition",
    "going to a handmade soap workshop",
    "learning to make shadow boxes",
    "visiting a perfume making workshop",
    "going to a kite making workshop",
    "learning to do leather crafting",
    "visiting a natural dye workshop",
    "watching a breakdance competition",
    "going to a candle making workshop",
    "learning to create mosaic art",
    "visiting a shadow puppet performance",
    "going to a photo editing workshop",
    "learning to do calligraphy",
    "watching a sand art creation",
    "going to a weaving demonstration",
    "learning to make bobbin lace",
    "watching a dog agility competition"
]

export function GenerateExample() {
    return (examples[Math.floor(Math.random() * examples.length)])
}