const examples = [
    'barbecue with friends',
    'pool day with the family',
    'going to the beach with classmates',
    "long road trip adventure",
    "chill study session alone",
    "relaxing yoga retreat",
    "energetic morning run",
    "unwinding after work",
    "evening cooking dinner",
    "quiet reading time",
    "wild weekend party",
    "late-night gaming session",
    "snowy day indoors",
    "sunny afternoon picnic",
    "backyard camping night",
    "training for a marathon",
    "celebrating a promotion",
    "fun day at the zoo",
    "stargazing on a clear night",
    "holiday season shopping",
    "groovy dance practice",
    "exploring a new city",
    "packing for vacation",
    "decorating for Christmas",
    "cozy rainy day",
    "summer music festival",
    "hiking through the forest",
    "weekend gardening session",
    "candlelit dinner date",
    "bonfire with college friends",
    "lazy Sunday brunch",
    "intense weightlifting session",
    "prepping for a date",
    "midnight snack cooking",
    "sailing on the open sea",
    "fishing at the lake",
    "cleaning up the house",
    "studying for finals week",
    "cozy coffee shop vibes",
    "family reunion gathering",
    "baking cookies for Christmas",
    "night drive through the city",
    "afternoon painting session",
    "biking in the countryside",
    "cheering for your team",
    "preparing a birthday surprise",
    "meditating during sunset",
    "wine tasting in Napa",
    "mountain climbing challenge",
    "cuddling with pets",
    "watching a romantic movie",
    "exploring a flea market",
    "beach volleyball competition",
    "early bird breakfast making",
    "scary Halloween party",
    "first date at a café",
    "playing board games",
    "cooking a family recipe",
    "watching the sunrise",
    "karaoke night with friends",
    "relaxing at a spa",
    "prepping for a job interview",
    "skydiving adrenaline rush",
    "skating in the park",
    "enjoying a jazz concert",
    "writing a new novel",
    "visiting grandparents' house",
    "building a snowman",
    "camping in the wilderness",
    "celebrating a wedding anniversary",
    "visiting a farmers market",
    "backpacking through Europe",
    "wine and paint night",
    "movie marathon weekend",
    "cheering at a sports game",
    "DIY home renovation",
    "celebrating a new job",
    "surfing at the beach",
    "romantic walk in the park",
    "learning a new language",
    "brewing some homemade beer",
    "watching a comedy show",
    "planting new spring flowers",
    "strolling through an art museum",
    "cozying up with a book",
    "observing a quiet snowfall",
    "shopping in downtown",
    "visiting a theme park",
    "tailgating at the game",
    "stargazing at the observatory",
    "scuba diving adventure",
    "playing video games",
    "building a model ship",
    "hosting a charity event",
    "ice-skating in winter",
    "fall leaf peeping trip",
    "making homemade pizza",
    "crafting DIY gifts",
    "volunteering at the shelter",
    "throwing a surprise party"
    ]
export function GenerateExample() {
    return (examples[Math.floor(Math.random() * examples.length)])
}