name: deploy-to-lambda

on:
  push:
    branches:
      - main
    paths:
    - 'server/**'

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: npm install and build
        env:
          CI: true
        run: |
          cd server
          npm install && npm run build
      - name: deploy
        run: |
          cd server
          zip -r function.zip node_modules dist
          aws lambda update-function-code --function-name=generatePlaylist --zip-file=fileb://function.zip
